Repository log4js-node/log4js-node, pull requests merged in 2022-01, with the labels that each got.

#1127 test: update fakeFS.read as graceful-fs uses it
  test/tap/configuration-test.js
Labels: tests

#1128 test: update fakeFS.read as graceful-fs uses it
  test/tap/configuration-test.js
Labels: tests

#1129 chore(deps-dev): bump eslint-config-prettier from 6.15.0 to 8.3.0
  package-lock.json
  package.json
  test/tap/file-sighup-test.js
  test/tap/tcp-appender-test.js
Labels: dependencies

#1130 chore(deps): update deps
  package-lock.json
  package.json
Labels: dependencies

#1134 chore(deps): bump date-format from 3.0.0 to 4.0.2
  package-lock.json
  package.json
Labels: dependencies

#1135 chore(deps): bump streamroller from 2.2.4 to 3.0.1
  package-lock.json
  package.json
Labels: dependencies

#1136 chore(deps-dev): bump fs-extra from 8.1.0 to 10.0.0
  package-lock.json
  package.json
Labels: dependencies

#1137 chore(deps): bump flatted from 2.0.2 to 3.2.4
  package-lock.json
  package.json
Labels: dependencies

#1138 chore(deps-dev): bump eslint from 5.16.0 to 8.6.0
  package-lock.json
  package.json
Labels: dependencies

#1140 chore(deps-dev): bump nyc from 14.1.1 to 15.1.0
  package-lock.json
  package.json
  test/sandbox-coverage.js
Labels: dependencies

#1142 test: added assertion for increase of SIGHUP listeners on log4js.configure()
  test/tap/file-sighup-test.js
Labels: tests

#1022 test(improvement): Add tearDown to unit tests
  test/tap/configuration-validation-test.js
Labels: tests

#1143 chore(test): update teardown() for tests to remove tmp files
  package.json
  test/tap/configuration-validation-test.js
  test/tap/dateFileAppender-test.js
  test/tap/file-descriptor-leak-test.js
  test/tap/file-sighup-test.js
  test/tap/fileAppender-test.js
  test/tap/fileSyncAppender-test.js
  test/tap/multi-file-appender-test.js
  test/tap/pause-test.js
Labels: tests

#1145 chore(deps-dev): bump eslint from from 8.6.0 to 8.7.0
  package-lock.json
  package.json
Labels: dependencies

#1146 chore(deps): bump date-format from 4.0.2 to 4.0.3
  package-lock.json
  package.json
Labels: dependencies

#1147 chore(deps): bump streamroller from 3.0.1 to 3.0.2
  package-lock.json
  package.json
Labels: dependencies

#1153 chore(docs): changed author to contributors in package.json
  package.json
Labels: documentation

#1168 chore: updated changelog for 6.4.1
  CHANGELOG.md
Labels: documentation

#1170 test(multiprocess): add e2e test
  test/multiprocess-worker.js
  test/tap/multiprocess-test.js
Labels: tests

#1172 refactor(test): replaced tap deprecation in preparation for tap v15
  test/tap/configuration-inheritance-test.js
  test/tap/configuration-validation-test.js
  test/tap/dateFileAppender-test.js
  test/tap/file-descriptor-leak-test.js
  test/tap/file-sighup-test.js
  test/tap/fileAppender-test.js
  test/tap/fileSyncAppender-test.js
  test/tap/logLevelFilter-test.js
  test/tap/logging-test.js
  test/tap/multi-file-appender-test.js
  test/tap/pause-test.js
Labels: tests

#1173 chore(dep): bump tap from 14.10.7 to 15.1.6
  package-lock.json
  package.json
  test/tap/appender-dependencies-test.js
  test/tap/categoryFilter-test.js
  test/tap/cluster-test.js
  test/tap/configuration-test.js
  test/tap/configuration-validation-test.js
  test/tap/connect-context-test.js
  test/tap/connect-logger-test.js
  test/tap/connect-nolog-test.js
  test/tap/dateFileAppender-test.js
  test/tap/disable-cluster-test.js
  test/tap/fileAppender-test.js
  test/tap/fileSyncAppender-test.js
  test/tap/logger-test.js
  test/tap/multi-file-appender-test.js
  test/tap/multiprocess-test.js
  test/tap/newLevel-test.js
  test/tap/noLogFilter-test.js
Labels: dependencies

#1181 chore(docs) - updated dateFile appender docs
  docs/dateFile.md
Labels: documentation

#1182 chore(docs) - updated file appender doc
  docs/file.md
Labels: documentation
