Repository log4js-node/log4js-node, pull requests merged in 2022-10, with the labels that each got.

#1332 fix(LoggingEvent): serde for `NaN`, `Infinity`, `-Infinity`, `undefined`
  lib/LoggingEvent.js
  lib/connect-logger.js
  lib/logger.js
  test/tap/LoggingEvent-test.js
  test/tap/logLevelFilter-test.js
Labels: bug

#1334 feat(log4js): if cb is passed to `shutdown()`, it must be a function or it will throw error immediately
  .github/workflows/node.js.yml
  docs/api.md
  lib/log4js.js
  test/tap/logging-test.js
Labels: enhancement

#1335 docs: updated changelog for 6.7.0
  CHANGELOG.md
Labels: documentation

#1338 Fix typo
  docs/layouts.md
Labels: documentation
