Repository log4js-node/log4js-node, pull requests merged in 2022-03, with the labels that each got.

#1191 Fixed fileSync appender to create directory recursively
  lib/appenders/fileSync.js
  test/tap/fileSyncAppender-test.js
Labels: bug

#1194 chore(deps): updated dev-dep
  package-lock.json
  package.json
Labels: dependencies

#1202 chore(docs): updated file and fileSync appender docs
  docs/file.md
  docs/fileSync.md
Labels: documentation

#1200 chore(test): improve test coverage
  lib/appenders/fileSync.js
  lib/appenders/index.js
  lib/appenders/multiFile.js
  test/tap/configuration-validation-test.js
  test/tap/default-settings-test.js
  test/tap/file-descriptor-leak-test.js
  test/tap/file-sighup-test.js
  test/tap/fileAppender-test.js
  test/tap/fileSyncAppender-test.js
  test/tap/logging-test.js
  test/tap/multi-file-appender-test.js
  test/tap/multiprocess-test.js
  test/tap/recordingAppender-test.js
  test/tap/server-test.js
  types/test.ts
Labels: tests

#1203 chore(docs): updated logger api docs
  docs/api.md
Labels: documentation

#1204 chore(test): improve test coverage
  test/tap/dateFileAppender-test.js
  test/tap/fileSyncAppender-test.js
  test/tap/multi-file-appender-test.js
  test/tap/pause-test.js
  test/tap/tcp-appender-test.js
Labels: tests

#1205 chore(test): improve test coverage
  lib/appenders/fileSync.js
  lib/logger.js
  test/tap/connect-logger-test.js
  test/tap/dateFileAppender-test.js
  test/tap/file-sighup-test.js
  test/tap/fileAppender-test.js
  test/tap/logger-test.js
Labels: tests

#1207 chore(dep): updated dependencies
  lib/LoggingEvent.js
  lib/appenders/adapters.js
  package-lock.json
  package.json
  test/tap/connect-context-test.js
  test/tap/connect-logger-test.js
  test/tap/connect-nolog-test.js
  test/tap/dateFileAppender-test.js
  test/tap/file-descriptor-leak-test.js
  test/tap/file-sighup-test.js
  test/tap/fileAppender-test.js
  test/tap/multi-file-appender-test.js
  test/tap/server-test.js
Labels: dependencies

#1208 chore(docs): added docs for istanbul ignore
  lib/appenders/index.js
  lib/appenders/multiFile.js
  lib/logger.js
Labels: documentation

#1211 chore(test): improved test cases
  lib/appenders/index.js
  lib/layouts.js
  test/tap/default-settings-test.js
  test/tap/file-sighup-test.js
  test/tap/layouts-test.js
  test/tap/multi-file-appender-test.js
Labels: tests

#1212 chore(docs): updated changelog for 6.4.3
  CHANGELOG.md
Labels: documentation

#1217 chore(fix): set logger.level on runtime will no longer reset useCallStack
  lib/categories.js
  lib/logger.js
  test/tap/logger-test.js
Labels: bug

#985 Update Loading mechanism instruction #1
  docs/writing-appenders.md
Labels: documentation

#1221 chore(dep): updated dependencies
  package-lock.json
  package.json
Labels: dependencies
