Repository log4js-node/log4js-node, pull requests merged in 2022-09, with the labels that each got.

#1316 FEAT: patternLayout function name, class name and function alias
  docs/layouts.md
  lib/LoggingEvent.js
  lib/layouts.js
  lib/logger.js
  test/tap/LoggingEvent-test.js
  test/tap/layouts-test.js
  test/tap/logger-test.js
Labels: enhancement

#1318 test: adjusted timeout interval for OS operations
  test/tap/multi-file-appender-test.js
Labels: tests

#1321 docs(migration-guide): fix typo (`have been remove` --> `have been removed`)
  docs/migration-guide.md
Labels: documentation

#1322 docs(noLogFilter): fix heading (`Category Filter` --> `No-Log Filter`)
  docs/noLogFilter.md
Labels: documentation

#1327 chore(deps): updated dependencies
  package-lock.json
  package.json
Labels: dependencies

#1329 chore(deps-dev): updated dependencies
  docs/_layouts/default.html
  docs/connect-logger.md
  docs/layouts.md
  examples/custom-layout.js
  examples/hipchat-appender.js
  examples/patternLayout-tokens.js
  lib/appenders/dateFile.js
  lib/appenders/file.js
  lib/appenders/multiprocess.js
  lib/appenders/recording.js
  lib/appenders/tcp.js
  lib/layouts.js
  lib/logger.js
  package-lock.json
  package.json
  test/sandbox-coverage.js
  test/tap/configuration-inheritance-test.js
  test/tap/configuration-validation-test.js
  test/tap/connect-logger-test.js
  test/tap/connect-nolog-test.js
  test/tap/default-settings-test.js
  test/tap/file-sighup-test.js
  test/tap/layouts-test.js
  test/tap/logger-test.js
  test/tap/logging-test.js
  test/tap/multi-file-appender-test.js
  test/tap/tcp-appender-test.js
  types/test.ts
Labels: dependencies

#1330 chore(deps): bump typescript from 4.8.3 to 4.8.4
  package.json
Labels: dependencies

#1269 Add ability to use passed in Errors for callstacks and adjust how deeply you want to look for information
  docs/api.md
  lib/LoggingEvent.js
  lib/logger.js
  test/tap/LoggingEvent-test.js
  test/tap/logger-test.js
  types/log4js.d.ts
Labels: enhancement
