Repository log4js-node/log4js-node, pull requests merged in 2022-07, with the labels that each got.

#1280 fix: load CJS appenders for ESM packages
  lib/appenders/index.js
  test/tap/dummy-appender.cjs
Labels: bug

#1279 feat: adding function(req, res) support to connectLogger options->nol…
  docs/connect-logger.md
  lib/connect-logger.js
  test/tap/connect-nolog-test.js
Labels: enhancement

#1283 docs: updated changelog for 6.6.0
  CHANGELOG.md
Labels: documentation

#1293 test: support older Node.js versions
  test/sandbox-coverage.js
  test/tap/layouts-test.js
Labels: tests

#1295 test: support older Node.js versions
  test/sandbox-coverage.js
  test/tap/fileAppender-test.js
  test/tap/fileSyncAppender-test.js
  test/tap/layouts-test.js
  test/tap/multiprocess-shutdown-test.js
Labels: tests

#1296 chore(deps): updated dependencies
  package-lock.json
  package.json
Labels: dependencies

#1297 test: support older Node.js versions
  test/tap/fileAppender-test.js
Labels: tests

#1298 chore(deps-dev): bump eslint from 8.16.0 to 8.20.0
  package.json
Labels: dependencies

#1301 ci: added tests for Node.js 10.x, 18.x
  .github/workflows/node.js.yml
  package-lock.json
  package.json
Labels: tests

#1303 ci: added tests for Node.js 8.x
  .github/workflows/node.js.yml
  .prettierignore
  docs/_layouts/default.html
  docs/connect-logger.md
  docs/layouts.md
  examples/custom-layout.js
  examples/hipchat-appender.js
  examples/patternLayout-tokens.js
  lib/appenders/dateFile.js
  lib/appenders/file.js
  lib/appenders/multiprocess.js
  lib/appenders/recording.js
  lib/appenders/tcp.js
  lib/layouts.js
  lib/logger.js
  package-lock.json
  package.json
  test/tap/appender-dependencies-test.js
  test/tap/categoryFilter-test.js
  test/tap/configuration-inheritance-test.js
  test/tap/configuration-test.js
  test/tap/configuration-validation-test.js
  test/tap/connect-context-test.js
  test/tap/connect-logger-test.js
  test/tap/connect-nolog-test.js
  test/tap/default-settings-test.js
  test/tap/file-sighup-test.js
  test/tap/layouts-test.js
  test/tap/logger-test.js
  test/tap/logging-test.js
  test/tap/multi-file-appender-test.js
  test/tap/multiprocess-test.js
  test/tap/newLevel-test.js
  test/tap/noLogFilter-test.js
  test/tap/tcp-appender-test.js
  types/test.ts
Labels: tests

#1305 chore(deps-dev): downgraded nyc from 15.1.0 to 14.1.1
  package-lock.json
  package.json
  test/sandbox-coverage.js
Labels: dependencies

#1306 test: extended timeout interval for OS operations
  test/tap/dateFileAppender-test.js
  test/tap/file-descriptor-leak-test.js
  test/tap/file-sighup-test.js
  test/tap/fileAppender-test.js
  test/tap/logLevelFilter-test.js
  test/tap/multi-file-appender-test.js
Labels: tests

#1307 docs: updated changelog for 6.6.1
  CHANGELOG.md
Labels: documentation
