Repository log4js-node/log4js-node, pull requests merged in 2022-06, with the labels that each got.

#1266 chore(deps): updated dependencies
  package-lock.json
  package.json
Labels: dependencies

#1267 Make Appender Type extensible from other modules and the user
  .editorconfig
  .gitattributes
  package.json
  types/log4js.d.ts
  types/test.ts
Labels: enhancement

#1272 docs: renamed myself in changelog
  CHANGELOG.md
Labels: documentation
